### PR TITLE
Refactor preload to handle more cases

### PR DESCRIPTION
**Pull request by cesarizu**
Hello,

I've modified the preload module to accept more use cases. I was having some problem with null properties and some combinations of pre-loading objects and arrays. Please let me know what you think.

The cases supported now are:
* `preload(thing, <string>)`
* `preload(thing, [ <string | object>, ... ])`
* `preload(thing, { property: <string | array | object>, ... })`

Previously some of these combinations where not supported.

Cheers!

### CODE REVIEW

**Comment by mike-north** [comment]
Love the idea of handling more cases. Could you please

* Describe the new cases you aim to support
* Write some tests for them

**Comment by cesarizu** [comment]
I've updated the description and I'll add some tests soon.

**Comment by mike-north** [comment]
👍

**Comment by cesarizu** [comment]
@mike-north, I've updated the PR with some extra tests.

**Comment by mike-north** [comment]
This looks great, thanks!

**Pull request merged**
